version: '3.9'

services:
  web:
    build:
      context: .
    image: ghcr.io/reflejar/adminorg-front:latest
    volumes:
      - .:/app
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    command: npm run dev
