export const receiptTypes = [
    { id: 'Factura A', full_name: 'Factura A' },
    { id: 'Factura B', full_name: 'Factura B' },
    { id: 'Factura C', full_name: 'Factura C' },
    { id: 'Factura X', full_name: 'Factura X' },
    { id: 'Nota de Debito A', full_name: 'Nota de Debito A' },
    { id: 'Nota de Debito B', full_name: 'Nota de Debito B' },
    { id: 'Nota de Debito C', full_name: 'Nota de Debito C' },
    { id: 'Nota de Credito A', full_name: 'Nota de Credito A' },
    { id: 'Nota de Debito X', full_name: 'Nota de Debito X' },
    { id: 'Nota de Credito B', full_name: 'Nota de Credito B' },
    { id: 'Nota de Credito C', full_name: 'Nota de Credito C' },
    { id: 'Nota de Credito X', full_name: 'Nota de Credito X' },
    { id: 'Liquidacion A', full_name: 'Liquidacion A' },
    { id: 'Liquidacion B', full_name: 'Liquidacion B' },
    { id: 'Recibo X', full_name: 'Recibo X' },
    { id: 'Orden de Pago X', full_name: 'Orden de Pago X' },
    { id: 'Retencion', full_name: 'Retencion' },
    { id: 'Transferencia X', full_name: 'Transferencia X' },
    { id: 'Asiento', full_name: 'Asiento' },
];
