export const provincias = [
    { id: null, nombre: "---"},
    { id: "Ciudad Autónoma de Buenos Aires", nombre: "Ciudad Autónoma de Buenos Aires"},
    { id: "Buenos Aires", nombre: "Buenos Aires"},
    { id: "Catamarca", nombre: "Catamarca"},
    { id: "Córdoba", nombre: "Córdoba"},
    { id: "Corrientes", nombre: "Corrientes"},
    { id: "Entre Ríos", nombre: "Entre Ríos"},
    { id: "Jujuy", nombre: "Jujuy"},
    { id: "Mendoza", nombre: "Mendoza"},
    { id: "La Rioja", nombre: "La Rioja"},
    { id: "Salta", nombre: "Salta"},
    { id: "San Juna", nombre: "San Juna"},
    { id: "San Luis", nombre: "San Luis"},
    { id: "Santa Fe", nombre: "Santa Fe"},
    { id: "Santiago del Estero", nombre: "Santiago del Estero"},
    { id: "Tucumán", nombre: "Tucumán"},
    { id: "Chaco", nombre: "Chaco"},
    { id: "Chubut", nombre: "Chubut"},
    { id: "Formosa", nombre: "Formosa"},
    { id: "Misiones", nombre: "Misiones"},
    { id: "Neuquén", nombre: "Neuquén"},
    { id: "La Pampa", nombre: "La Pampa"},
    { id: "Río Negro", nombre: "Río Negro"},
    { id: "Santa Cruz", nombre: "Santa Cruz"},
    { id: "Tierra del Fuego", nombre: "Tierra del Fuego"}
];
